In [1]:
import numpy as np

In [4]:
np.arange(1, 10, 0.5)

array([1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. , 6.5, 7. ,
       7.5, 8. , 8.5, 9. , 9.5])

In [6]:
np.linspace(1,10,num=5,endpoint=True)

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [ ]:
np.repeat('a',repeats= 5) #repeats가 정수냐 아니면 배열로 들어가느냐에 따라서 어떤것을 반복할지로 바뀜
np.repeat([1,2,3,4],4)

array([1, 1, 1, 1, 2, 2, 2, 2, 3, 3, 3, 3, 4, 4, 4, 4])

In [10]:
# 타일과 repeat의 차이
np.tile([1,3,4,5], 3)

array([1, 3, 4, 5, 1, 3, 4, 5, 1, 3, 4, 5])

In [20]:
arr = np.array([[1,2], [3,4]])

np.repeat(arr, 3, axis=0)

array([[1, 2],
       [1, 2],
       [1, 2],
       [3, 4],
       [3, 4],
       [3, 4]])

In [27]:
arr.size
len(arr)

2

In [29]:
matrix = np.column_stack((np.arange(1,5),np.arange(12,16)))
matrix

array([[ 1, 12],
       [ 2, 13],
       [ 3, 14],
       [ 4, 15]])

In [ ]:
# 연습문제

In [40]:
np.random.seed(2005)
vec = np.random.choice(np.arange(1,101), size = 3000, replace= True)

mat = vec.reshape(-1,2)
mat

array([[10,  2],
       [96, 26],
       [47, 48],
       ...,
       [53, 53],
       [84, 61],
       [ 8, 87]])

In [ ]:
# Q1. 중간고사 평균과 기말고사 평균은?
np.mean(mat[:,0]) ,np.mean(mat[:,1])

#mid_avg = mat[:,0].mean(), fin_avg = mat[:,1].mean()
#res = mat.mean(axis=0)
#mid_avg = res[0] fin_avg = res[1]

#02. 중간고사 성적이 50이상인 학생들의 데이터를 걸러내보세요. 몇명인가요?
midsc_50 = mat[mat[:,0] >= 50]
len(up) #mat[mat[:, 0] >= 50].shape[0]

#len(mat[mat[:0] >- 50, :])
#Q3 그 학생들의 기말고사 성적 평균은?
np.mean(up[:, 1])

#mat[mat[:0] >= 50,1].mean()
#Q4. 중간고사 최고점을 맞은 학생의 기말고사 성적은?
mat[np.argmax(mat[:,0])][1]

#mid_score = mat[:,0]
#fin_score = mat[:,1]
#mat[mat == max(mid_score), 1]  문제의 오류임  인원수 채크해서하이튼 해야함

#05. 중간고사 성적이 평균보다 높은 학생들의 기말고사 성적 평균은?
np.sum(mat[:, 1] > mat[:, 0])

#mat[mat[mid_score > mid_avg]].mean

#Q6. 중간고사 대비 기말고사 성적이 향상된 학생들은 몇명인가요?
len(np.where(mat[:, 1] < mat[:, 0])[0])

#sum(mid+score < fin_score)

#Q7. 반대로 성적이 떨어진 학생들은 어디에 위치해 있나요? 학번(인덱스) 정보

#std = np.where(mat[:,0] > mat[:, 1])[0]
#std[:10]
#mat[std, :]

array([   0,    1,    4,    5,    6,    9,   12,   15,   17,   18,   20,
         22,   26,   28,   33,   34,   35,   37,   39,   40,   41,   43,
         45,   47,   51,   52,   54,   60,   61,   64,   70,   71,   72,
         73,   75,   77,   78,   80,   81,   84,   86,   88,   91,   92,
         93,   94,   95,   98,   99,  100,  102,  105,  115,  116,  117,
        118,  120,  122,  123,  125,  127,  128,  129,  131,  134,  135,
        136,  142,  144,  145,  146,  149,  152,  153,  154,  156,  159,
        161,  165,  168,  171,  173,  175,  176,  178,  181,  182,  185,
        186,  187,  189,  192,  194,  195,  198,  200,  203,  207,  208,
        211,  212,  214,  217,  218,  219,  220,  222,  224,  227,  228,
        229,  230,  231,  232,  233,  234,  236,  237,  238,  239,  240,
        247,  248,  250,  251,  252,  254,  258,  259,  260,  261,  262,
        263,  265,  266,  267,  268,  269,  272,  273,  275,  276,  280,
        282,  283,  284,  285,  287,  288,  289,  2